# Generated by Django 4.2 on 2024-08-22 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0021_alter_product_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["product", "description", "category", "price"],
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
            },
        ),
    ]
